# Generated by Django 3.0.6 on 2020-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('destination', models.GenericIPAddressField(verbose_name='Destination')),
                ('source', models.GenericIPAddressField(verbose_name='source')),
            ],
        ),
    ]
