# Generated by Django 3.0.6 on 2020-05-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip', models.GenericIPAddressField(verbose_name='Source host')),
                ('dip', models.GenericIPAddressField(verbose_name='Destination host')),
                ('srcpkts', models.IntegerField(verbose_name='Count frames from sip -> dip')),
                ('drcpkts', models.IntegerField(verbose_name='Count frames from dip -> sip')),
            ],
        ),
        migrations.AlterField(
            model_name='frame',
            name='source',
            field=models.GenericIPAddressField(verbose_name='Source'),
        ),
    ]
