# Generated by Django 3.0.6 on 2020-05-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200531_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='degree_centrality',
        ),
        migrations.AddField(
            model_name='node',
            name='betweenness_centrality',
            field=models.FloatField(null=True, verbose_name='Betweenness centrality'),
        ),
        migrations.AddField(
            model_name='node',
            name='closeness_centrality',
            field=models.FloatField(null=True, verbose_name='Closeness centrality'),
        ),
        migrations.AddField(
            model_name='node',
            name='clustering_coefficient',
            field=models.FloatField(null=True, verbose_name='Clustering coefficient'),
        ),
        migrations.AddField(
            model_name='node',
            name='eigenvector_centrality',
            field=models.FloatField(null=True, verbose_name='Eigenvector centrality'),
        ),
        migrations.AlterField(
            model_name='node',
            name='incoming_weight',
            field=models.IntegerField(null=True, verbose_name='Incoming weight'),
        ),
        migrations.AlterField(
            model_name='node',
            name='outgoing_weight',
            field=models.IntegerField(null=True, verbose_name='Outgoing weight'),
        ),
    ]
