# Generated by Django 3.0.6 on 2020-05-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200531_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='alpha_centrality',
            field=models.FloatField(null=True, verbose_name='Alpha centrality'),
        ),
    ]
